### ISSUE TITLE
Include Community guidelines and Installation instructions in the Readme

### ISSUE THREAD

**Issue by HerrMo** [lutz-hamel/popsom#11]
In my opinion, it would be good practice to include installation instructions in the Readme, for example:

### Installation

Install the last release from CRAN:

```
install.packages("popsom")
```

 Moreover, I think a note on how to contribute/report bugs is missing.

**Comment by lutzhamel** [comment]
There is a file called CONTRIBUTING.md that details how to participate in this project.
