### ISSUE TITLE
Split up package code to improve readability

### ISSUE THREAD

**Issue by rcannood** [lutz-hamel/popsom#13]
The package consists of a very large R file which makes navigation of the functions in the package difficult. Following common R practices, I suggest splitting this file up into multiple R files, ideally one file per function.

Please consider generating the man/* files using [roxygen2](https://roxygen2.r-lib.org/articles/roxygen2.html#basic-process-1). Having the documentation close to the functions allow developers to easily interpret the functionality of each function.

**Comment by fabian-s** [comment]
I fully agree with the first part (multiple thematically focussed files are better than one huge file), but if  @lutzhamel does not want to do this, it won't block acceptance. Same for roxygenizing the docs.

**Comment by lutzhamel** [comment]
The software package has been stable for the better part of a decade.  At this point I am not inclined to rearchitect its software structure.

**Comment by rcannood** [comment]
Ok with me. 

If you do ever come back to separating the functions into separate files (which should not be that much work), converting the 'man/*' files to roxygen2 documentation is quite straightforward if you use `Rd2roxygen::Rd2roxygen('path/to/source/pkg')`.

**Comment by lutzhamel** [comment]
Thanks for the pointer.  I will bear it in mind.
