### ISSUE TITLE
Provide a high-level description of SOM

### ISSUE THREAD

**Issue by rcannood** [lutz-hamel/popsom#15]
Summary does not contain a high-level description of the package functionality other than that it provides an implementation of self-organising maps and that a self-organising map is an artificial neural network designed for unsupervised learning. This is insufficient information to get a high-level idea of what SOMs are and what they are commonly used for.

**Comment by fabian-s** [comment]
In my view, this is a reasonable request to improve the readability of the paper. 
A 2-3 sentence summary of what SOMs do would help readers understand how and when to use this software.

**Comment by lutzhamel** [comment]
Rewrote the 'Background' section to include a high-level statement of what SOMs do.

**Comment by rcannood** [comment]
Thanks a lot!
