### ISSUE TITLE
Statement of need is missing

### ISSUE THREAD

**Issue by rcannood** [lutz-hamel/popsom#16]
The authors statement of need is more of a results section. The only statement of need in this paragraph is: "Training a self-organizing map is time consuming." Authors should expand on how training SOMs is time consuming: which application domains? what is the dimensionality of such datasets resulting in the slow execution time?

**Comment by fabian-s** [comment]
I agree with @rcanood that the statement of need could focus more on the gaps in available software implementation that popsom fills and less on what popsom itself does, but the two are obviously strongly linked. 



The two implicit statement of needs being made here are:
- usability of existing packages suffers from computations being too slow and popsom improves that by being 1 to 2 magnitudes faster
- SOMs are mostly not very useful without good visualisations so popsom includes an improved viz method that is not available from any other package.

As far as algorithmic efficiency is concerned, I do think it would be helpful to talk about the scaling behavior of popsom in the number of data points and their dimension and compare that to alternatives. I don't think it would necessarily be very helpful to list application domains or data set sizes, there are some timings at the end of the paper for toy datasets, after all. 

For the viz aspect, I think the current phrasing is fine.

**Comment by lutzhamel** [comment]
Rewrote the part of the statement of need that talks about speedups.

**Comment by rcannood** [comment]
Great, thanks!

**Comment by fabian-s** [comment]
@lutzhamel sorry if I'm overlooking something but I don't think these changes are showing up in your GH repo yet -- the last commit is 6d old. 
Could you try to push all your latest commits so we can generate the updated paper?

**Comment by lutzhamel** [comment]
@whedon generate pdf
